### PR TITLE
Pass `str` into `error!`

### LINKED ISSUE #6: the trait `ToValue` is not implemented for `std::string::String`
After upgrading log to 0.4.14, json_env_logger won't compile:

```
error[E0277]: the trait bound `std::string::String: ToValue` is not satisfied
  --> /home/acim/.cargo/registry/src/github.com-1ecc6299db9ec823/json_env_logger-0.1.1/src/lib.rs:79:21
   |
79 | /                     kv_log_macro::error!(
80 | |                         "panicked at '{}'", msg,
81 | |                         {
82 | |                             thread: thread,
83 | |                             location: format!("{}:{}", location.file(), location.line())
84 | |                         }
85 | |                     );
   | |______________________^ the trait `ToValue` is not implemented for `std::string::String`
   |
   = note: required for the cast to the object type `dyn ToValue`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `json_env_logger`
```

### PR DESCRIPTION
**Pull request by tcharding**
Recently during an upgrade of `log` it appears that the `ToValue` implementation for `String` was removed. There is still an implementation for `str`.

Use `as_str` to convert argument of `error!` to a string reference.

Example error:
```
error[E0277]: the trait bound `std::string::String: ToValue` is not satisfied
  --> /home/tobin/build/github.com/tcharding/json-env-logger/src/lib.rs:79:21
   |
79 | /                     kv_log_macro::error!(
80 | |                         "panicked at '{}'", msg,
81 | |                         {
82 | |                             thread: thread,
83 | |                             location: format!("{}:{}", location.file(), location.line())
84 | |                         }
85 | |                     );
   | |______________________^ the trait `ToValue` is not implemented for `std::string::String`
   |

```

Fixes: #6

### CODE REVIEW

**Comment by tcharding** [comment]
This has been open for almost a year now, closing.
